config/routes.rb
Rails.application.routes.draw do
  resources :trip_images 

    resources :trips

end

app/models/trip.rb
class Trip < ActiveRecord::Base
	has_many :trip_images, dependent: :destroy
	accepts_nested_attributes_for :trip_images, allow_destroy: true

end

app/models/trip_image.rb
class TripImage < ActiveRecord::Base
	attr_accessor :photo
	belongs_to :trip
	has_attached_file :photo,
	path: ":rails_root/public/images/:id/:filename",
	url:  "/images/:id/:filename",
	styles: { 
		#resize imagen full ancho y alto fijo
		# small: ["100x100!", :jpg],
		# medium: ["250x250!"],
		# large: ["500x500!", :jpg]
		#crop imagen 
		# small: ["100x100#", :jpg, quality: 70],
		# medium: ["250x250#"],
		# large: ["500x500#", :jpg, quality: 70]
		# resize imagen proporcional 
		small: "100x100>",
		medium: "250x250>",
		large: "500x500>",
		extralarge: "1280x1000>",
		
		},
		convert_options: {
			all: '-quality 75',
			# small: '-colorspace Gray -resize 200x200 ',
			# medium: '-colorspace Gray -resize 200x200 ',
			# large: '-radial-blur 4 -resize 200x200 '
		}
		validates_attachment_file_name :photo, matches: [/png\Z/, /jpe?g\Z/]

	end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trip_images_controller.rb
class TripImagesController < ApplicationController
  before_action :set_trip_image, only: [:show, :edit, :update, :destroy]

  # GET /trip_images
  # GET /trip_images.json
  def index
    @trip_images = TripImage.all
  end

  # GET /trip_images/1
  # GET /trip_images/1.json
  def show
  end

  # GET /trip_images/new
  def new
    @trip_image = TripImage.new
  end

  # GET /trip_images/1/edit
  def edit
  end

  # POST /trip_images
  # POST /trip_images.json
  def create
    @trip_image = TripImage.new(trip_image_params)

    respond_to do |format|
      if @trip_image.save
        format.html { redirect_to @trip_image, notice: 'Trip image was successfully created.' }
        format.json { render :show, status: :created, location: @trip_image }
      else
        format.html { render :new }
        format.json { render json: @trip_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trip_images/1
  # PATCH/PUT /trip_images/1.json
  def update
    respond_to do |format|
      if @trip_image.update(trip_image_params)
        format.html { redirect_to @trip_image, notice: 'Trip image was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip_image }
      else
        format.html { render :edit }
        format.json { render json: @trip_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trip_images/1
  # DELETE /trip_images/1.json
  def destroy
    @trip_image.destroy
    respond_to do |format|
      format.html { redirect_to trip_images_url, notice: 'Trip image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip_image
      @trip_image = TripImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_image_params
      params.require(:trip_image).permit(:trip_id)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @gallery  = Trip.find(params[:id])
    @pictures = @gallery.trip_images
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end

  end

  # GET /trips/new
  def new
    @trip = Trip.new
    @trip.trip_images.build
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
    5.times {@trip.trip_images.build}
    
  end



  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(title:  params[:title])
    respond_to do |format|
      if @trip.save
        if params[:photos]
          # The magic is here ;)
          params[:photos].each { |image|
            @trip.trip_images.create(photo: image)
          }
        end
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trip_images_helper.rb
module TripImagesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paperclip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trip_images/_form.html.erb
<%= form_for(@trip_image) do |f| %>
  <% if @trip_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip_image.errors.count, "error") %> prohibited this trip_image from being saved:</h2>

      <ul>
      <% @trip_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :trip_id %><br>
    <%= f.number_field :trip_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trip_images/edit.html.erb
<h1>Editing trip_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip_image %> |
<%= link_to 'Back', trip_images_path %>

app/views/trip_images/index.html.erb
<h1>Listing trip_images</h1>

<table>
  <thead>
    <tr>
      <th>Trip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trip_images.each do |trip_image| %>
      <tr>
        <td><%= trip_image.trip_id %></td>
        <td><%= link_to 'Show', trip_image %></td>
        <td><%= link_to 'Edit', edit_trip_image_path(trip_image) %></td>
        <td><%= link_to 'Destroy', trip_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip image', new_trip_image_path %>

app/views/trip_images/new.html.erb
<h1>New trip_image</h1>

<%= render 'form' %>

<%= link_to 'Back', trip_images_path %>

app/views/trip_images/show.html.erb
<div class="row">
  <h1>Gallery</h1>

  <input type="hidden" id="galleryID" value="<%= @gallery.id %>">

  
  <p>
    <b>Description: </b>
    <%= @gallery.description %>
  </p>

<h2>Pictures</h2>
</div>

<div class="row">
  <ul class="thumbnails files">
<% unless @pictures.empty? %>
  <% @pictures.each do |pic| %>
    <li class="span3" id="picture_<%= pic.id %>">
    <div class="thumbnail">
      <%= image_tag pic.image.url %>
      <div class="caption">
        <p style="text-align: center;">
        <%= link_to "Edit", trip_image_path(pic) %>

        <%= 
          link_to "Delete", pic, 
            :data => { :confirm => "Are you sure?" }, 
            :method => :delete 
          %>

        </p>
      </div>
    </div>
    </li>
  <% end %>
<% end %>
</ul>
</div>


<div class="row">
  <div class="form-actions">
    <%= link_to 'Back', galleries_path, :class => 'btn btn-mini'  %>
    <%= link_to 'Edit', edit_gallery_path(@gallery), :class => 'btn btn-mini' %>
    <%= link_to 'Delete', gallery_path(@gallery), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-mini' %>
  </div>
</div>

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<h1>Listing trips</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.title %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<%= form_for @trip, :html => { multipart: true } do |f| %>
<div class="control-group">
	<%= f.label :title, :class => 'control-label' %>
	<div class="controls">
		<%= f.text_field :title, :class => 'text_field' %>
	</div>
</div>
<!--  <div class="control-group">
	<%= f.label :tripimages, :class => 'control-label' %>
	<div class="controls">
		<%= file_field_tag "photos[]", type: :file, multiple: true %>
	</div>
</div>
 -->
 <div class="newPaperclipFiles">

	<%= 7.times do |i| %>
	<div class="controls">
		<%= file_field_tag "photos[]", type: :file, multiple: false %>
	</div>
	
	<% end %>


</div> 

<div class="form-actions">
	<%= f.submit nil, :class => 'btn btn-primary' %>
	<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
	trips_path, :class => 'btn btn-mini' %>
</div>




<% end %>

app/views/trips/show.html.erb
<div class="row">
  <h1>Gallery</h1>

  <input type="hidden" id="galleryID" value="<%= @gallery.id %>">

  
  <p>
    <b>Description: </b>
    <%= @gallery.id %>
  </p>

<h2>Pictures</h2>
</div>

<div class="row">
  <ul class="thumbnails files">
<% unless @pictures.empty? %>
  <% @pictures.each do |pic| %>
    <li class="span3" id="picture_<%= pic.id %>">
    <div class="thumbnail">
      <%= image_tag pic.photo.url %>
      <div class="caption">
        <p style="text-align: center;">
        <%= link_to "Edit", trip_image_path(pic) %>

        <%= 
          link_to "Delete", pic, 
            :data => { :confirm => "Are you sure?" }, 
            :method => :delete 
          %>

        </p>
      </div>
    </div>
    </li>
  <% end %>
<% end %>
</ul>
</div>


<div class="row">
  <div class="form-actions">
    <%= link_to 'Back', trips_path, :class => 'btn btn-mini'  %>
    <%= link_to 'Edit', edit_trip_path(@gallery), :class => 'btn btn-mini' %>
    <%= link_to 'Delete', trip_path(@gallery), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-mini' %>
  </div>
</div>